#!/usr/bin/env python3
# Generated by AtCoder Tools 2.8.0
# Copyright 2021 Yuichiro Smith

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, S: "List[str]", T: "List[str]"):
    unique_set = set(zip(S, T))
    print(YES if len(unique_set) != N else NO)


def main():
    # Failed to predict input format
    N = int(input().strip())
    S, T = zip(*(input().split() for _ in range(N)))
    solve(N, S, T)


if __name__ == '__main__':
    main()
