#!/usr/bin/env python3
# Generated by AtCoder Tools 2.8.0
# Copyright 2021 Yuichiro Smith
import sys

MOD = 5  # type: int


def solve(m: int):
    return


def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    m = int(next(tokens))  # type: int
    solve(m)


if __name__ == '__main__':
    main()
