#!/usr/bin/env python3
# Generated by AtCoder Tools 2.8.0
# Copyright 2021 Yuichiro Smith


def solve(X: int, Y: int):
    if 0 <= Y <= 2:
        print(f"{X}-")
    if 3 <= Y <= 6:
        print(f"{X}")
    if 7 <= Y <= 9:
        print(f"{X}+")


def main():
    # Failed to predict input format
    X, Y = map(int, input().split("."))
    solve(X, Y)


if __name__ == '__main__':
    main()
