#!/usr/bin/env python3
# Generated by AtCoder Tools 2.8.0
# Copyright 2021 Yuichiro Smith


def solve(N2: int, N3: int, N4: int):
    N1 = N2
    N2 = N4
    N3 //= 2

    p23 = min(N2, N3)
    N3 -= p23
    N2 -= p23

    p113 = min(N1//2, N3)
    N3 -= p113
    N1 -= p113*2

    p122 = min(N1, N2//2)
    N2 -= p122*2
    N1 -= p122

    p1112 = min(N1//3, N2)
    N2 -= p1112
    N1 -= p1112*3

    p11111 = N1//5
    N1 -= p11111*5

    print(p23 + p113 + p122 + p1112 + p11111)


def main():
    T = int(input())
    for _ in range(T):
        solve(*map(int, input().split()))


if __name__ == '__main__':
    main()
