#!/usr/bin/env python3
# Generated by 2.6.0
# Copyright 2021 Yuichiro Smith

MOD = 998244353  # type: int


def main():
    # Failed to predict input format
    pass


if __name__ == '__main__':
    main()
