#!/usr/bin/env python3
# Generated by AtCoder Tools 2.8.0
# Copyright 2021 Yuichiro Smith
import sys


def solve(N: int):
    sums = 0
    marker_l = 1
    while marker_l <= N:
        marker_r1 = marker_l
        marker_r2 = marker_r1 + 1
        while marker_r1 <= N:
            sums += min(marker_r2, N+1)-marker_r1
            marker_r1 *= 10
            marker_r2 *= 10
        marker_l *= 10
        marker_l += 1
    print(sums)


def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
