#!/usr/bin/env python3
# Generated by AtCoder Tools 2.8.0
# Copyright 2021 Yuichiro Smith

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N, _M, _K, A):
    graph = [0] * N
    for a in A:
        for j, x in enumerate(a[1:]):
            j += 1
            y = a[j-1]
            x, y = x-1, y-1

            self = 1 << x
            depends = 1 << y
            if self & graph[y]:
                return print(NO)
            graph[j] |= graph[j-1] | depends
    print(YES)


def main():
    # Failed to predict input format
    N, M = map(int, input().split())
    K = []
    A = []
    for _ in range(M):
        K.append(int(input()))
        A.append(list(map(int, input().split())))
    solve(N, M, K, A)


if __name__ == '__main__':
    main()
