#!/usr/bin/env python3
# Generated by 2.6.0
# Copyright 2021 Yuichiro Smith
import sys


def solve(_N: int, A: "List[int]"):
    # インデックスを含めたものをソートして
    A_sorted = sorted(enumerate(A), key=lambda a: a[1])
    booby_idx, _ = A_sorted[-2]
    print(booby_idx + 1)
    return


def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)


if __name__ == '__main__':
    main()
