#!/usr/bin/env python3
# Generated by 2.6.0
# Copyright 2021 Yuichiro Smith
import sys


def solve(H: int, W: int, N: int, A: "List[int]", B: "List[int]"):
    # 座標圧縮: 1-indexed
    x_map = {a: x+1 for x, a in enumerate(sorted(set(A)))}
    y_map = {b: x+1 for x, b in enumerate(sorted(set(B)))}
    for a, b in zip(A, B):
        print(x_map[a], y_map[b])
    return


def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    A = [int()] * (N)  # type: "List[int]"
    B = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(H, W, N, A, B)


if __name__ == '__main__':
    main()
