#!/usr/bin/env python3
# Generated by 2.6.0
# Copyright 2021 Yuichiro Smith


def solve(H: int, W: int, Map: "List[List[str]]"):
    print(H, W, Map)


def main():
    # Failed to predict input format
    H, W = map(int, input().split())
    Map = [
        list(input())
        for _ in range(H)
    ]
    return solve(H, W, Map)


if __name__ == '__main__':
    main()
