#!/usr/bin/env python3
# Generated by AtCoder Tools 2.8.0
# Copyright 2021 Yuichiro Smith
import sys


def solve(P: "List[int]"):
    print("".join(map(lambda n: chr(ord("a") + n-1), P)))
    return


def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    P = [int(next(tokens)) for _ in range(26)]  # type: "List[int]"
    solve(P)


if __name__ == '__main__':
    main()
